import type { Metadata } from 'next'
import './../globals.css'
import TopBar from './../components/Topbar'
import Footer from './../components/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex flex-col w-full min-h-screen '>
        <TopBar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
